# Generated by Django 4.1.6 on 2023-02-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderplease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplease',
            name='country',
            field=models.CharField(blank=True, default='Sudan', max_length=120, null=True),
        ),
    ]
